In [2]:
import pickle, shap

with open("shap_values.pkl", "rb") as f:
    shap_values = pickle.load(f)

shap.plots.text(shap_values[0, :, 2])  # 第0条，对“利好”

In [5]:
import pickle
import shap

with open("shap_values_correct_100.pkl", "rb") as f:
    obj = pickle.load(f)

shap_values = obj["shap_values"]
meta = obj["data"]
label_order = obj["meta"]["label_order"]

i = 40
cls = label_order.index(meta[i]["pred"])

shap.plots.text(shap_values[i, :, cls])


In [6]:
import numpy as np
# 输出高置信度样本
# 假设 shap_values.base_values 可用
confidence = shap_values.base_values.max(axis=1)

top_idx = np.argsort(-confidence)[:5]
print(top_idx)


[0 1 2 3 4]


In [13]:
import pickle
import numpy as np

with open("shap_values_correct_100.pkl", "rb") as f:
    obj = pickle.load(f)

sv = obj["shap_values"]

print("values shape:", np.shape(sv.values))
print("base_values shape:", np.shape(sv.base_values))
print("type(sv.data):", type(sv.data))
print("len(sv.data):", len(sv.data))

# 看第0条样本的数据类型
print("type(data[0]):", type(sv.data[0]))
print("data[0] preview:", sv.data[0] if isinstance(sv.data[0], str) else sv.data[0][:20])

print("type(values[0]):", type(sv.values[0]))
print("values[0] =", sv.values[0])


values shape: (100,)
base_values shape: (100, 3)
type(sv.data): <class 'tuple'>
len(sv.data): 100
type(data[0]): <class 'numpy.ndarray'>
data[0] preview: ['成' '飞' '集成' '：' '9' '月' '9' '日' '融资' '买入' '37' '3' '5' '.' '24' '万元' '，'
 '融资' '融' '券']
type(values[0]): <class 'numpy.ndarray'>
values[0] = [[-6.00715767e-03 -2.14188686e-03  8.14904226e-03]
 [-6.00715767e-03 -2.14188686e-03  8.14904226e-03]
 [-5.16343786e-03 -1.02689909e-03  6.19033532e-03]
 [-5.16343786e-03 -1.02689909e-03  6.19033532e-03]
 [-1.71436390e-02  2.91288318e-02 -1.19851833e-02]
 [-1.75002877e-02  3.00986255e-02 -1.25983331e-02]
 [-9.24878177e-03  1.73138808e-02 -8.06509858e-03]
 [-7.21994037e-03  1.33650824e-02 -6.14514019e-03]
 [-1.04196690e-02  1.18194794e-02 -1.39981239e-03]
 [-1.77862567e-02 -3.59652620e-03  2.13827804e-02]
 [ 4.46619652e-03 -1.29994860e-02  8.53328921e-03]
 [ 4.44774411e-03 -1.29453026e-02  8.49755797e-03]
 [ 4.55187028e-03 -1.81226415e-02  1.35707674e-02]
 [ 3.38649354e-03 -4.75863181e-03  1.372

In [14]:
import numpy as np

abs_sample = np.abs(np.array(sv.values)).reshape(-1)
top_idx = np.argsort(-abs_sample)[:10]
top_idx, abs_sample[top_idx]


ValueError: operands could not be broadcast together with shapes (53,3) (95,3) 